// brain/server.js
//
// The BeCopenhagen data brain — a STANDALONE service.
//
// Deliberately independent of the fleet app: its own express instance, its
// own pm2 process, its own port. If this crashes, the fleet app doesn't
// notice. It reads the fleet database READ-ONLY and can never write to it.
//
// Env (in brain/.env):
//   BRAIN_PORT=3001
//   BRAIN_EMAIL=federico@becopenhagen.dk
//   BRAIN_PASSWORD_HASH=<from `node hash-password.js`>
//   BRAIN_SESSION_SECRET=<any long random string>
//   ANTHROPIC_API_KEY_REPORTS=sk-ant-...
//   FLEET_DB=/var/www/becopenhagen-fleet/data/fleet.db

require('dotenv').config({ path: require('path').join(__dirname, '.env') });

const express = require('express');
const session = require('express-session');
const FileStore = require('session-file-store')(session);
const crypto = require('crypto');
const path = require('path');
const fs = require('fs');
const { execFile } = require('child_process');
const { DatabaseSync } = require('node:sqlite');

const PORT = process.env.BRAIN_PORT || 3001;
const DB_PATH = path.join(__dirname, 'analytics.db');
const UPLOAD_DIR = path.join(__dirname, 'uploads');
const FLEET_DB =
  process.env.FLEET_DB || '/var/www/becopenhagen-fleet/data/fleet.db';
const API_KEY =
  process.env.ANTHROPIC_API_KEY_REPORTS || process.env.ANTHROPIC_API_KEY;
const MODEL = process.env.BRAIN_MODEL || 'claude-sonnet-5';

fs.mkdirSync(UPLOAD_DIR, { recursive: true });

const app = express();
app.set('trust proxy', 1);
app.use(express.json({ limit: '60mb' }));
// Sessions are stored on disk, not in memory — otherwise every pm2 restart
// logs everyone out (and the resulting 401s masquerade as other bugs).
// NOTE: BRAIN_SESSION_SECRET must be set in .env; without it, a random
// secret per boot would invalidate all cookies on restart anyway.
app.use(
  session({
    store: new FileStore({ path: path.join(__dirname, 'sessions'), ttl: 60 * 60 * 24 * 30, logFn: () => {} }),
    secret: process.env.BRAIN_SESSION_SECRET || crypto.randomBytes(32).toString('hex'),
    resave: false,
    saveUninitialized: false,
    cookie: { maxAge: 1000 * 60 * 60 * 24 * 30, sameSite: 'lax' },
  })
);

// --- auth -----------------------------------------------------------------
// Password is never stored in plaintext, only as a scrypt hash generated by
// hash-password.js. The brain never sees or logs the password itself.
function verifyPassword(password, stored) {
  if (!stored || !stored.includes(':')) return false;
  const [saltHex, keyHex] = stored.split(':');
  const salt = Buffer.from(saltHex, 'hex');
  const expected = Buffer.from(keyHex, 'hex');
  const actual = crypto.scryptSync(password, salt, expected.length);
  return crypto.timingSafeEqual(expected, actual);
}

app.post('/api/login', (req, res) => {
  const { email, password } = req.body || {};
  const okEmail =
    String(email || '').trim().toLowerCase() ===
    String(process.env.BRAIN_EMAIL || '').trim().toLowerCase();
  let okPass = false;
  try {
    okPass = verifyPassword(String(password || ''), process.env.BRAIN_PASSWORD_HASH);
  } catch (_) {
    okPass = false;
  }
  if (okEmail && okPass) {
    req.session.user = process.env.BRAIN_EMAIL;
    return res.json({ ok: true });
  }
  // Same message either way — don't reveal which field was wrong.
  res.status(401).json({ error: 'Wrong email or password.' });
});

app.post('/api/logout', (req, res) => {
  req.session.destroy(() => res.json({ ok: true }));
});

function requireAuth(req, res, next) {
  if (req.session?.user) return next();
  res.status(401).json({ error: 'Not logged in.' });
}

// --- database -------------------------------------------------------------
function openDb() {
  if (!fs.existsSync(DB_PATH)) {
    const e = new Error('No data loaded yet — upload your CSV exports first.');
    e.code = 'NO_DB';
    throw e;
  }
  const db = new DatabaseSync(DB_PATH, { readOnly: true });

  // Attach the live fleet DB read-only. mode=ro means SQLite itself refuses
  // any write — the fleet app's data cannot be modified from here.
  if (fs.existsSync(FLEET_DB)) {
    try {
      db.exec(`ATTACH DATABASE 'file:${FLEET_DB}?mode=ro' AS fleet`);
    } catch (e) {
      console.warn('[brain] fleet DB not attached:', e.message);
    }
  }
  return db;
}

function runSelect(sql) {
  if (!/^\s*(select|with)\b/i.test(sql)) throw new Error('Only SELECT queries are allowed.');
  if (/\b(insert|update|delete|drop|alter|create|attach|detach|pragma|vacuum)\b/i.test(sql)) {
    throw new Error('Query contains a forbidden keyword.');
  }
  const db = openDb();
  try {
    return db.prepare(sql).all();
  } finally {
    db.close();
  }
}

// --- Claude ---------------------------------------------------------------
// Read fresh on every question, so editing context.md takes effect
// immediately — no restart, no redeploy.
function buildSystem() {
  const schema = fs.readFileSync(path.join(__dirname, 'schema.txt'), 'utf8');
  let context = '';
  try {
    context = fs.readFileSync(path.join(__dirname, 'context.md'), 'utf8');
  } catch (_) {}

  return `You are the data analyst for BeCopenhagen, a Copenhagen bike tour
and rental company. You answer Federico's questions by querying a SQLite database.

${context ? '=== BUSINESS CONTEXT (authoritative — trust this over your own assumptions) ===\n' + context + '\n' : ''}
=== DATABASE SCHEMA ===
${schema}

Process:
1. Work out what's really being asked (mind the booked_dow vs tour_dow trap).
2. Emit your SQL inside <sql></sql> tags. Read-only SELECT only.
   - Usually ONE query is right.
   - For broad questions ("analyse the business", "where are the opportunities")
     you may emit up to 5 separate <sql> blocks, each answering one facet.
     Keep each one SHORT and focused. Do not write one giant query.
3. You'll get all the rows back, then you explain the answer in prose.

Keep queries compact. A query that needs more than ~15 lines is a sign you're
trying to do too much in one go — split it or simplify it.

If a question needs no query, just answer it.

LEARNING
If Federico tells you something about the business you didn't know — a
correction, a rule, a definition, a piece of context that would change how you
answer similar questions in future — propose it as a memory by emitting:

<remember>the fact as ONE short standalone sentence</remember>

Rules for this:
- ONE LINE. One fact. Short. Never a paragraph, never multiple facts bundled
  together — each fact must be independently true, editable and deletable.
- Only for DURABLE business knowledge (how the business works, what a product
  is, a rule, a correction of something you got wrong).
- NEVER for one-off query results, numbers you just computed, or anything
  already in the data — the data is queried live and doesn't need remembering.
- Only when he actually tells you something. Don't propose memories from your
  own inferences or from what a query returned.
- Write it so it stands alone and still makes sense months from now with no
  conversation around it.
- At most one per reply. If nothing qualifies, emit nothing. Most replies
  should have no <remember> at all.

Style: direct, concrete, lead with the answer. Cite real numbers. Flag caveats
that genuinely matter (small sample, discontinued product, data gap) but don't
pad with disclaimers. Money in DKK. If the data can't answer it, say so plainly
rather than guessing.`;
}

async function callClaude(messages, maxTokens = 8000) {
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'x-api-key': API_KEY,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({ model: MODEL, max_tokens: maxTokens, system: buildSystem(), messages }),
  });
  if (!res.ok) throw new Error(`Anthropic API ${res.status}: ${(await res.text()).slice(0, 300)}`);
  const data = await res.json();
  const text = data.content.filter((b) => b.type === 'text').map((b) => b.text).join('');
  // stop_reason 'max_tokens' means the reply was cut off mid-sentence — the
  // caller must know, or it will render half a thought (or half a query).
  return { text, truncated: data.stop_reason === 'max_tokens' };
}

// Pull every SQL block out of a reply. Tolerates an unclosed final tag, which
// is what a truncated response looks like.
function extractSql(text) {
  const out = [];
  const re = /<sql>([\s\S]*?)(?:<\/sql>|$)/gi;
  let m;
  while ((m = re.exec(text)) !== null) {
    const q = m[1].trim();
    if (q) out.push(q);
  }
  return out;
}

// Strip SQL and memory markup, closed or not, so nothing raw ever reaches
// the user.
function stripMarkup(text) {
  return text
    .replace(/<sql>[\s\S]*?(?:<\/sql>|$)/gi, '')
    .replace(/<remember>[\s\S]*?(?:<\/remember>|$)/gi, '')
    .trim();
}

// --- routes ---------------------------------------------------------------
app.post('/api/ask', requireAuth, async (req, res) => {
  if (!API_KEY) return res.status(500).json({ error: 'ANTHROPIC_API_KEY_REPORTS is not set.' });
  const { question, history = [] } = req.body || {};
  if (!question || !String(question).trim()) return res.status(400).json({ error: 'Ask me something.' });

  try {
    const messages = [
      ...history.slice(-6).map((m) => ({ role: m.role, content: m.content })),
      { role: 'user', content: String(question) },
    ];

    let { text: reply, truncated } = await callClaude(messages);

    // If the model ran out of room mid-query, ask it to be more economical
    // rather than rendering a half-written statement.
    if (truncated && extractSql(reply).length === 0) {
      messages.push({ role: 'assistant', content: stripMarkup(reply) || '(cut off)' });
      messages.push({ role: 'user', content: 'That got cut off. Answer again, more concisely.' });
      ({ text: reply, truncated } = await callClaude(messages));
    }

    let queries = extractSql(reply);
    const results = [];

    if (queries.length) {
      for (const sql of queries.slice(0, 5)) {   // a few queries, not unbounded
        try {
          results.push({ sql, rows: runSelect(sql), error: null });
        } catch (e) {
          results.push({ sql, rows: null, error: e.message });
        }
      }

      // Let it repair any query that failed — once.
      if (results.some((r) => r.error)) {
        const broken = results.filter((r) => r.error)
          .map((r) => `Query:\n${r.sql}\nError: ${r.error}`).join('\n\n');
        messages.push({ role: 'assistant', content: reply });
        messages.push({
          role: 'user',
          content: `These queries failed:\n\n${broken}\n\nEmit corrected SQL in <sql></sql> tags (only the ones that failed).`,
        });
        const fix = await callClaude(messages);
        const fixed = extractSql(fix.text);
        let fi = 0;
        for (const r of results) {
          if (r.error && fixed[fi]) {
            try {
              r.rows = runSelect(fixed[fi]);
              r.sql = fixed[fi];
              r.error = null;
            } catch (e) {
              r.error = e.message;
            }
            fi++;
          }
        }
      }

      // Hand the rows back for interpretation. Cap what we send so a huge
      // result set can't blow the context window.
      const payload = results.map((r, i) => {
        if (r.error) return `Query ${i + 1} failed: ${r.error}`;
        const shown = r.rows.slice(0, 100);
        return `Query ${i + 1} returned ${r.rows.length} row(s)` +
               (r.rows.length > shown.length ? ` (first ${shown.length} shown)` : '') +
               `:\n${JSON.stringify(shown, null, 2)}`;
      }).join('\n\n');

      messages.push({ role: 'assistant', content: reply });
      messages.push({
        role: 'user',
        content: `${payload}\n\nNow answer my original question using these numbers. Do not write any more SQL.`,
      });

      const final = await callClaude(messages);
      reply = final.text;
    }

    // Memory proposal — surfaced for approval, never written silently.
    let learned = null;
    const rm = reply.match(/<remember>([\s\S]*?)(?:<\/remember>|$)/i);
    if (rm && rm[1].trim()) learned = rm[1].trim();

    const answer = stripMarkup(reply);

    // Show the first result set as a table; list the rest of the queries.
    const primary = results.find((r) => r.rows && r.rows.length);

    res.json({
      answer: answer || 'I could not put that into words — try asking a narrower question.',
      sql: results.map((r) => r.sql).join('\n\n---\n\n') || null,
      queryCount: results.length,
      rows: primary ? primary.rows.slice(0, 25) : null,
      rowCount: primary ? primary.rows.length : 0,
      learned,
    });
  } catch (e) {
    if (e.code === 'NO_DB') return res.status(409).json({ error: e.message });
    console.error('[brain] ask failed:', e.message);
    res.status(500).json({ error: e.message });
  }
});

app.get('/api/status', requireAuth, (req, res) => {
  if (!fs.existsSync(DB_PATH)) return res.json({ loaded: false });
  try {
    const db = openDb();
    const b = db.prepare('SELECT COUNT(*) n, MAX(booked_at) hi FROM bookings').get();
    let fleetOk = false;
    try {
      db.prepare('SELECT 1 FROM fleet.tour_availabilities LIMIT 1').get();
      fleetOk = true;
    } catch (_) {}
    db.close();

    // Recommended export window: from ONE WEEK BEFORE the last data day (the
    // overlap catches late changes to recent bookings — cancellations,
    // payments) through today. Merge-mode dedupes the overlap.
    let exportFrom = null;
    if (b.hi) {
      const d = new Date(b.hi);
      d.setDate(d.getDate() - 7);
      exportFrom = d.toISOString().slice(0, 10);
    }
    res.json({
      loaded: true,
      bookings: b.n,
      bookings_to: b.hi ? String(b.hi).slice(0, 10) : null,
      export_from: exportFrom,
      today: new Date().toISOString().slice(0, 10),
      fleet: fleetOk,
    });
  } catch (e) {
    res.json({ loaded: false, error: e.message });
  }
});

// --- upload: one pile of files, identified by their own headers ---
// Each FareHarbor report has a distinctive column signature, so the user
// never assigns files to slots (and can never get them crossed):
//   'Payment or Refund ID'  -> sales
//   'Customer type'         -> customers
//   'Cancelled?' (and neither of the above) -> bookings
function sniffReport(text) {
  const head = text.slice(0, 6000);
  if (head.includes('Payment or Refund ID')) return 'sales';
  if (head.includes('Customer type')) return 'customers';
  if (head.includes('Cancelled?') && head.includes('Booking ID')) return 'bookings';
  return null;
}

// Basic sanity: parses, has rows, and covers a plausible date range.
function validateReport(text, kind) {
  const lines = text.split('\n').filter(l => l.trim());
  if (lines.length < 10) return `${kind}: file has almost no rows — wrong export?`;
  // Detailed exports have a Booking ID / txn ID column; Summary exports don't.
  if (kind === 'bookings' && !text.includes('Booking ID')) {
    return 'bookings: no Booking ID column — did you export Summary instead of Detailed?';
  }
  return null;
}

// Detect a wrong "Report on" basis. A correct incremental export (reported on
// created date) has its CREATED dates confined to the export window. A
// wrong-basis export (run on Availability date) drags in bookings CREATED
// months or years back. Warning, not rejection: a deliberate full-history
// re-upload also spans years and must stay allowed — the discriminator is
// that full history is thousands of rows, a weekly slice is not.
// Uses the same real CSV parser as the loader — naive comma-splitting
// misreads any field containing a comma.
const { parseCsv } = require('./load');

function checkBasis(text, kind) {
  let rows;
  try { rows = parseCsv(text); } catch (_) { return null; }
  if (rows.length < 3) return null;
  const totalRows = rows.length - 2;   // full row count decides "deliberate full upload"
  const header = rows[1].map(h => h.replace(/^\uFEFF/, '').trim());
  const idx = header.indexOf('Created At Date');
  if (idx < 0) return null;

  const dates = [];
  for (let i = 2; i < Math.min(rows.length, 3000); i++) {
    const v = (rows[i][idx] || '').trim();
    let m = v.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);
    if (m) { dates.push(`${m[3]}-${m[2]}-${m[1]}`); continue; }
    m = v.match(/^(\d{4})-(\d{2})-(\d{2})/);
    if (m) dates.push(v.slice(0, 10));
  }
  if (dates.length < 5) return null;

  dates.sort();
  const span = (new Date(dates[dates.length - 1]) - new Date(dates[0])) / 86400000;
  if (span > 90 && totalRows < 2500) {
    return `${kind}: created dates span ${Math.round(span)} days across only ${totalRows} rows — if this was meant as a weekly export, it was probably run on "Availability date" instead of "created date". (Fine if you meant to upload a longer history.)`;
  }

  // Second fingerprint, catches availability-basis exports of ANY size:
  // a created-basis bookings export always contains bookings for FUTURE tour
  // dates (people book ahead). If the max tour date is capped at the max
  // created date, the export window was applied to availability dates and the
  // entire forward pipeline is missing.
  if (kind === 'bookings') {
    const si = header.indexOf('Start Date');
    if (si >= 0) {
      let maxStart = '', maxCreated = '';
      for (let i = 2; i < rows.length; i++) {
        const sd = (rows[i][si] || '').trim().slice(0, 10);
        const cd = (rows[i][idx] || '').trim().slice(0, 10);
        if (sd > maxStart) maxStart = sd;
        if (cd > maxCreated) maxCreated = cd;
      }
      if (maxStart && maxCreated && maxStart <= maxCreated) {
        return `bookings: no future-dated tours at all (latest tour ${maxStart}, latest created ${maxCreated}) — this export was almost certainly run on "Availability date" instead of "Booking created date". Future bookings are missing, which blinds pace and forward-look analysis. Re-export with Report on: Booking created date.`;
      }
    }
  }
  return null;
}

app.post('/api/upload', requireAuth, (req, res) => {
  const { files } = req.body || {};
  if (!Array.isArray(files) || !files.length) {
    return res.status(400).json({ error: 'No files received.' });
  }

  const found = {};   // kind -> { name, text }
  const problems = [];

  for (const f of files) {
    const kind = sniffReport(f.text || '');
    if (!kind) {
      problems.push(`"${f.name}" doesn't look like any FareHarbor report I know — skipped.`);
      continue;
    }
    if (found[kind]) {
      problems.push(`Two files both look like the ${kind} report ("${found[kind].name}" and "${f.name}") — using the first.`);
      continue;
    }
    const bad = validateReport(f.text, kind);
    if (bad) { problems.push(bad); continue; }
    const basis = checkBasis(f.text, kind);
    if (basis) problems.push(basis);
    found[kind] = { name: f.name, text: f.text };
  }

  if (!found.bookings || !found.sales) {
    const missing = ['bookings', 'sales'].filter(k => !found[k]).join(' and ');
    return res.status(400).json({
      error: `Missing the ${missing} report. ` + (problems.length ? problems.join(' ') : ''),
    });
  }

  const bPath = path.join(UPLOAD_DIR, 'bookings.csv');
  const sPath = path.join(UPLOAD_DIR, 'sales.csv');
  const cPath = path.join(UPLOAD_DIR, 'customers.csv');
  try {
    fs.writeFileSync(bPath, found.bookings.text, 'utf8');
    fs.writeFileSync(sPath, found.sales.text, 'utf8');
    if (found.customers) fs.writeFileSync(cPath, found.customers.text, 'utf8');
  } catch (e) {
    return res.status(500).json({ error: 'Could not save uploads: ' + e.message });
  }

  const args = [path.join(__dirname, 'load.js'), bPath, sPath];
  if (found.customers) args.push(cPath);
  args.push('--db', DB_PATH);

  execFile(process.execPath, args, { timeout: 180000 }, (err, stdout, stderr) => {
    if (err) {
      console.error('[brain] load failed:', stderr || err.message);
      return res.status(500).json({ error: 'Load failed: ' + String(stderr || err.message).slice(0, 400) });
    }
    const detected = Object.entries(found).map(([k, v]) => `${v.name} → ${k}`).join(', ');
    res.json({
      ok: true,
      message: String(stdout || '').trim(),
      detected,
      warnings: problems,
      customers_included: !!found.customers,
    });
  });
});


// Business context — editable from the UI so knowledge can be fixed the
// moment the brain gets something wrong.
const CONTEXT_PATH = path.join(__dirname, 'context.md');

app.get('/api/context', requireAuth, (req, res) => {
  try {
    res.json({ text: fs.readFileSync(CONTEXT_PATH, 'utf8') });
  } catch (e) {
    res.json({ text: '' });
  }
});

app.put('/api/context', requireAuth, (req, res) => {
  const { text } = req.body || {};
  if (typeof text !== 'string') return res.status(400).json({ error: 'Nothing to save.' });
  try {
    fs.writeFileSync(CONTEXT_PATH, text, 'utf8');
    res.json({ ok: true });
  } catch (e) {
    res.status(500).json({ error: 'Could not save: ' + e.message });
  }
});

// Commit an approved memory. Appended under a dated "Learned" section so
// there's always an audit trail of what the brain was taught and when.
app.post('/api/remember', requireAuth, (req, res) => {
  const { fact } = req.body || {};
  if (!fact || !String(fact).trim()) return res.status(400).json({ error: 'Nothing to remember.' });

  const clean = String(fact).trim().replace(/\s+/g, ' ');
  const today = new Date().toISOString().slice(0, 10);

  try {
    let text = fs.readFileSync(CONTEXT_PATH, 'utf8');
    const HEADING = '## Learned in conversation';
    if (!text.includes(HEADING)) {
      text += `\n\n${HEADING}\n\nThings Federico taught the brain while chatting. Edit or delete freely.\n`;
    }
    text += `\n- ${clean} (verified ${today})\n`;
    fs.writeFileSync(CONTEXT_PATH, text, 'utf8');
    res.json({ ok: true });
  } catch (e) {
    res.status(500).json({ error: 'Could not save: ' + e.message });
  }
});

// --- review flow: confirm the facts Claude asserted from memory ---
// Anything tagged (unverified) was written by Claude, not by Federico, and
// should not be trusted until he says so.

app.get('/api/unverified', requireAuth, (req, res) => {
  try {
    const text = fs.readFileSync(CONTEXT_PATH, 'utf8');
    const facts = text.split('\n')
      .map((line, i) => ({ line, i }))
      .filter(({ line }) => /^\s*-\s+.*\(unverified\)\s*$/i.test(line))
      .map(({ line, i }) => ({
        id: i,
        text: line.replace(/^\s*-\s+/, '').replace(/\s*\(unverified\)\s*$/i, '').trim(),
      }));
    res.json({ facts });
  } catch (e) {
    res.json({ facts: [] });
  }
});

// verdict: 'confirm' | 'delete' | 'edit' (with newText)
app.post('/api/verify', requireAuth, (req, res) => {
  const { id, verdict, newText } = req.body || {};
  try {
    const lines = fs.readFileSync(CONTEXT_PATH, 'utf8').split('\n');
    if (typeof id !== 'number' || !lines[id]) return res.status(400).json({ error: 'No such line.' });

    if (verdict === 'delete') {
      lines.splice(id, 1);
    } else if (verdict === 'edit' && newText && newText.trim()) {
      lines[id] = '- ' + newText.trim().replace(/\s+/g, ' ') + ' (verified)';
    } else {
      lines[id] = lines[id].replace(/\s*\(unverified\)\s*$/i, ' (verified)');
    }

    fs.writeFileSync(CONTEXT_PATH, lines.join('\n'), 'utf8');
    res.json({ ok: true });
  } catch (e) {
    res.status(500).json({ error: 'Could not save: ' + e.message });
  }
});

// --- briefings: the analyst's autonomous weekly output ---
const { runAnalysis } = require('./analyst');
const BRIEF_DB = path.join(__dirname, 'briefings.db');
let analysisRunning = false;

app.get('/api/briefings', requireAuth, (req, res) => {
  if (!fs.existsSync(BRIEF_DB)) return res.json({ briefings: [] });
  try {
    const bdb = new DatabaseSync(BRIEF_DB, { readOnly: true });
    const rows = bdb.prepare('SELECT id, created_at, body FROM briefings ORDER BY id DESC LIMIT 12').all();
    bdb.close();
    res.json({ briefings: rows });
  } catch (e) {
    res.json({ briefings: [], error: e.message });
  }
});

app.post('/api/analyse', requireAuth, async (req, res) => {
  if (analysisRunning) return res.status(429).json({ error: 'An analysis is already running.' });
  analysisRunning = true;
  try {
    const { briefing, queriesRun } = await runAnalysis();
    res.json({ ok: true, briefing, queriesRun });
  } catch (e) {
    res.status(500).json({ error: e.message });
  } finally {
    analysisRunning = false;
  }
});

app.get('/api/me', (req, res) => res.json({ user: req.session?.user || null }));

app.use(express.static(path.join(__dirname, 'public')));
app.get('*', (req, res) => res.sendFile(path.join(__dirname, 'public/index.html')));

app.listen(PORT, () => {
  console.log(`[brain] listening on :${PORT}`);
  console.log(`[brain] fleet DB: ${fs.existsSync(FLEET_DB) ? FLEET_DB + ' (read-only)' : 'NOT FOUND — occupancy questions unavailable'}`);
  console.log(`[brain] analytics DB: ${fs.existsSync(DB_PATH) ? 'loaded' : 'empty — upload CSVs to populate'}`);
});
