// brain/server.js
//
// The BeCopenhagen data brain — a STANDALONE service.
//
// Deliberately independent of the fleet app: its own express instance, its
// own pm2 process, its own port. If this crashes, the fleet app doesn't
// notice. It reads the fleet database READ-ONLY and can never write to it.
//
// Env (in brain/.env):
//   BRAIN_PORT=3001
//   BRAIN_EMAIL=federico@becopenhagen.dk
//   BRAIN_PASSWORD_HASH=<from `node hash-password.js`>
//   BRAIN_SESSION_SECRET=<any long random string>
//   ANTHROPIC_API_KEY_REPORTS=sk-ant-...
//   FLEET_DB=/var/www/becopenhagen-fleet/data/fleet.db

require('dotenv').config({ path: require('path').join(__dirname, '.env') });

const express = require('express');
const session = require('express-session');
const crypto = require('crypto');
const path = require('path');
const fs = require('fs');
const { execFile } = require('child_process');
const { DatabaseSync } = require('node:sqlite');

const PORT = process.env.BRAIN_PORT || 3001;
const DB_PATH = path.join(__dirname, 'analytics.db');
const UPLOAD_DIR = path.join(__dirname, 'uploads');
const FLEET_DB =
  process.env.FLEET_DB || '/var/www/becopenhagen-fleet/data/fleet.db';
const API_KEY =
  process.env.ANTHROPIC_API_KEY_REPORTS || process.env.ANTHROPIC_API_KEY;
const MODEL = process.env.BRAIN_MODEL || 'claude-sonnet-5';

fs.mkdirSync(UPLOAD_DIR, { recursive: true });

const app = express();
app.set('trust proxy', 1);
app.use(express.json({ limit: '60mb' }));
app.use(
  session({
    secret: process.env.BRAIN_SESSION_SECRET || crypto.randomBytes(32).toString('hex'),
    resave: false,
    saveUninitialized: false,
    cookie: { maxAge: 1000 * 60 * 60 * 24 * 30, sameSite: 'lax' },
  })
);

// --- auth -----------------------------------------------------------------
// Password is never stored in plaintext, only as a scrypt hash generated by
// hash-password.js. The brain never sees or logs the password itself.
function verifyPassword(password, stored) {
  if (!stored || !stored.includes(':')) return false;
  const [saltHex, keyHex] = stored.split(':');
  const salt = Buffer.from(saltHex, 'hex');
  const expected = Buffer.from(keyHex, 'hex');
  const actual = crypto.scryptSync(password, salt, expected.length);
  return crypto.timingSafeEqual(expected, actual);
}

app.post('/api/login', (req, res) => {
  const { email, password } = req.body || {};
  const okEmail =
    String(email || '').trim().toLowerCase() ===
    String(process.env.BRAIN_EMAIL || '').trim().toLowerCase();
  let okPass = false;
  try {
    okPass = verifyPassword(String(password || ''), process.env.BRAIN_PASSWORD_HASH);
  } catch (_) {
    okPass = false;
  }
  if (okEmail && okPass) {
    req.session.user = process.env.BRAIN_EMAIL;
    return res.json({ ok: true });
  }
  // Same message either way — don't reveal which field was wrong.
  res.status(401).json({ error: 'Wrong email or password.' });
});

app.post('/api/logout', (req, res) => {
  req.session.destroy(() => res.json({ ok: true }));
});

function requireAuth(req, res, next) {
  if (req.session?.user) return next();
  res.status(401).json({ error: 'Not logged in.' });
}

// --- database -------------------------------------------------------------
function openDb() {
  if (!fs.existsSync(DB_PATH)) {
    const e = new Error('No data loaded yet — upload your CSV exports first.');
    e.code = 'NO_DB';
    throw e;
  }
  const db = new DatabaseSync(DB_PATH, { readOnly: true });

  // Attach the live fleet DB read-only. mode=ro means SQLite itself refuses
  // any write — the fleet app's data cannot be modified from here.
  if (fs.existsSync(FLEET_DB)) {
    try {
      db.exec(`ATTACH DATABASE 'file:${FLEET_DB}?mode=ro' AS fleet`);
    } catch (e) {
      console.warn('[brain] fleet DB not attached:', e.message);
    }
  }
  return db;
}

function runSelect(sql) {
  if (!/^\s*(select|with)\b/i.test(sql)) throw new Error('Only SELECT queries are allowed.');
  if (/\b(insert|update|delete|drop|alter|create|attach|detach|pragma|vacuum)\b/i.test(sql)) {
    throw new Error('Query contains a forbidden keyword.');
  }
  const db = openDb();
  try {
    return db.prepare(sql).all();
  } finally {
    db.close();
  }
}

// --- Claude ---------------------------------------------------------------
const SCHEMA = fs.readFileSync(path.join(__dirname, 'schema.txt'), 'utf8');

const SYSTEM = `You are the data analyst for BeCopenhagen, a Copenhagen bike tour
and rental company. You answer Federico's questions by querying a SQLite database.

${SCHEMA}

Process:
1. Work out what's really being asked (mind the booked_dow vs tour_dow trap).
2. Emit exactly ONE SQLite SELECT query inside <sql></sql> tags. Read-only.
3. You'll get the rows back, then explain the answer.

If a question needs no query, just answer it.

Style: direct, concrete, lead with the answer. Cite real numbers. Flag caveats
that genuinely matter (small sample, discontinued product, data gap) but don't
pad with disclaimers. Money in DKK. If the data can't answer it, say so plainly
rather than guessing.`;

async function callClaude(messages) {
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'x-api-key': API_KEY,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({ model: MODEL, max_tokens: 2000, system: SYSTEM, messages }),
  });
  if (!res.ok) throw new Error(`Anthropic API ${res.status}: ${(await res.text()).slice(0, 300)}`);
  const data = await res.json();
  return data.content.filter((b) => b.type === 'text').map((b) => b.text).join('');
}

// --- routes ---------------------------------------------------------------
app.post('/api/ask', requireAuth, async (req, res) => {
  if (!API_KEY) return res.status(500).json({ error: 'ANTHROPIC_API_KEY_REPORTS is not set.' });
  const { question, history = [] } = req.body || {};
  if (!question || !String(question).trim()) return res.status(400).json({ error: 'Ask me something.' });

  try {
    const messages = [
      ...history.slice(-6).map((m) => ({ role: m.role, content: m.content })),
      { role: 'user', content: String(question) },
    ];

    let reply = await callClaude(messages);
    let sql = null;
    let rows = null;

    const m = reply.match(/<sql>([\s\S]*?)<\/sql>/i);
    if (m) {
      sql = m[1].trim();
      try {
        rows = runSelect(sql);
      } catch (e) {
        messages.push({ role: 'assistant', content: reply });
        messages.push({
          role: 'user',
          content: `That query failed: ${e.message}\nFix it and emit corrected SQL in <sql></sql> tags.`,
        });
        reply = await callClaude(messages);
        const m2 = reply.match(/<sql>([\s\S]*?)<\/sql>/i);
        if (m2) {
          sql = m2[1].trim();
          rows = runSelect(sql);
        }
      }
    }

    let answer = reply;
    if (rows) {
      messages.push({ role: 'assistant', content: reply });
      messages.push({
        role: 'user',
        content:
          `Query returned ${rows.length} row(s):\n\n` +
          JSON.stringify(rows.slice(0, 200), null, 2) +
          `\n\nNow answer my original question using these numbers.`,
      });
      answer = await callClaude(messages);
    }

    answer = answer.replace(/<sql>[\s\S]*?<\/sql>/gi, '').trim();
    res.json({
      answer,
      sql,
      rows: rows ? rows.slice(0, 25) : null,
      rowCount: rows ? rows.length : 0,
    });
  } catch (e) {
    if (e.code === 'NO_DB') return res.status(409).json({ error: e.message });
    console.error('[brain] ask failed:', e.message);
    res.status(500).json({ error: e.message });
  }
});

app.get('/api/status', requireAuth, (req, res) => {
  if (!fs.existsSync(DB_PATH)) return res.json({ loaded: false });
  try {
    const db = openDb();
    const b = db.prepare('SELECT COUNT(*) n, MAX(booked_at) hi FROM bookings').get();
    let fleetOk = false;
    try {
      db.prepare('SELECT 1 FROM fleet.tour_availabilities LIMIT 1').get();
      fleetOk = true;
    } catch (_) {}
    db.close();
    res.json({ loaded: true, bookings: b.n, bookings_to: b.hi, fleet: fleetOk });
  } catch (e) {
    res.json({ loaded: false, error: e.message });
  }
});

app.post('/api/upload', requireAuth, (req, res) => {
  const { bookings_csv, sales_csv } = req.body || {};
  if (!bookings_csv || !sales_csv) {
    return res.status(400).json({ error: 'Both the bookings CSV and the sales CSV are required.' });
  }
  const bPath = path.join(UPLOAD_DIR, 'bookings.csv');
  const sPath = path.join(UPLOAD_DIR, 'sales.csv');
  try {
    fs.writeFileSync(bPath, bookings_csv, 'utf8');
    fs.writeFileSync(sPath, sales_csv, 'utf8');
  } catch (e) {
    return res.status(500).json({ error: 'Could not save uploads: ' + e.message });
  }

  execFile(
    process.execPath,
    [path.join(__dirname, 'load.js'), bPath, sPath, '--db', DB_PATH],
    { timeout: 180000 },
    (err, stdout, stderr) => {
      if (err) {
        console.error('[brain] load failed:', stderr || err.message);
        return res.status(500).json({ error: 'Load failed: ' + String(stderr || err.message).slice(0, 400) });
      }
      res.json({ ok: true, message: String(stdout || '').trim() });
    }
  );
});

app.get('/api/me', (req, res) => res.json({ user: req.session?.user || null }));

app.use(express.static(path.join(__dirname, 'public')));
app.get('*', (req, res) => res.sendFile(path.join(__dirname, 'public/index.html')));

app.listen(PORT, () => {
  console.log(`[brain] listening on :${PORT}`);
  console.log(`[brain] fleet DB: ${fs.existsSync(FLEET_DB) ? FLEET_DB + ' (read-only)' : 'NOT FOUND — occupancy questions unavailable'}`);
  console.log(`[brain] analytics DB: ${fs.existsSync(DB_PATH) ? 'loaded' : 'empty — upload CSVs to populate'}`);
});
